Updated app.py for resolving AttributeError
Importing load_model from tensorflow.keras.models instead of keras.models to solve this error `AttributeError: '_thread._local' object has no attribute 'value'` which was faced by many developers/